### ISSUE TITLE
Add link to elm-flatris

### ISSUE THREAD

**Issue by w0rm** [ptigwe/flatris#5]
Hey! I just stumbled upon this project, and found it surprising that modules and function names are the same as https://github.com/w0rm/elm-flatris but the readme only mentions the original Flatris.

I just feel it is a bit unfair to port things from the Elm version and not link to my work!

**Comment by ptigwe** [comment]
I've updated the Readme file to reflect the original source. I apologize for not including it in the first instance.

**Comment by w0rm** [comment]
@ptigwe cool, thank you!
